language: ruby
addons:
  apt:
    packages:
    - lmodern
    - make
    - pgf
    - texlive-bibtex-extra
    - texlive-fonts-extra
    - texlive-fonts-recommended
    - texlive-generic-extra
    - texlive-latex-base
    - texlive-latex-extra
    - texlive-latex-recommended
    - texlive-pictures
    - texlive-science
    - texlive-xcolor

script:
  - make
  - mkdir -p pdf
  - mv thesis.pdf pdf/

branches:
  only:
  - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: pdf
  on:
    branch: master
